server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}
 
#logging:
  #level: info
  #logstash:
  #  host: localhost
  #  port: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0

---
spring:
  profiles: docker
  #rabbitmq:
  #  host: rabbitmq
  #  port: 5672

#logging:
  #level: info
  #logstash:
  #  host: logstash
  #  port: 5000

eureka:
 client:
   serviceUrl:
     defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@eureka-server:8761/eureka}
 instance:
   preferIpAddress: true
   
spring:
  zipkin:
    base-url: http://zipkin-server:9411/
  sleuth:
    sampler:
      probability: 1.0