server:
  port: ${PORT:8082}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  metrics:
    export:
      appoptics:
        api-token: d1a331ee95302b4b078db6dea85a2ad3b1d8090466a4dc8c66d0ecd9dad42c97
        enabled: true
        step: 1m

spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0

customer-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 15000
    
logging:
  level:
    br.com.microservices.cardservice.client.CustomerClient: DEBUG   

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true
      
management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    CustomerClient#getTest():
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 5
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 5
      circuitBreaker:
        requestVolumeThreshold: 5