server:
  port: ${PORT:8082}

spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0

customer-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 15000
    
logging:
  level:
    br.com.microservices.cardservice.client.CustomerClient: DEBUG   

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true
      
management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    CustomerClient#getTest():
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 5
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 5
      circuitBreaker:
        requestVolumeThreshold: 5
---
spring:
  profiles: docker

spring:
  zipkin:
    base-url: http://zipkin-server:9411/
  sleuth:
    sampler:
      probability: 1.0
      
customer-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 15000
    
logging:
  level:
    br.com.microservices.cardservice.client.CustomerClient: DEBUG   

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true
      
management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    CustomerClient#getTest():
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 5
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 5
      circuitBreaker:
        requestVolumeThreshold: 5