server:
  port: ${PORT:8000}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    card-service:
      path: /card/**
      serviceId: card-service
    customer-service:
      path: /customer/**
      serviceId: customer-service

ribbon:
  eureka:
    enabled: true