server:
  port: ${PORT:8000}

spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    card-service:
      path: /card/**
      serviceId: card-service
    customer-service:
      path: /customer/**
      serviceId: customer-service

ribbon:
  eureka:
    enabled: true